### ISSUE TITLE
Infinite Loop With Lists and Relations

### ISSUE THREAD

**Issue by davidstoker** [nuwave/laravel-graphql-relay#20]
Hi, I've encountered an issue that results in an infinite loop and a segmentation fault with trying to use lists to definite simple relationships versus a Relay connection. Is there something I'm doing incorrectly for this situation or is this an issue? I could use a connection though in this use case there at most are 1-2 related objects so a connection is overkill and a list would be more appropriate.

I have a SessionType which has a list of payments for the one-to-many relationship. In `relayFields()` I'm returning this for payments:

```
'payments' => [
    'type' => Type::listOf(GraphQL::type('payment')),
    'description' => 'Payments for session',
    'resolve' => function (Session $session) {
        return $session->payments;
    }
],
```

In my PaymentType I then have the inverse:

```
'session' => [
    'type' => GraphQL::type('session'),
    'description' => 'Session that payment is connected to',
    'resolve' => function (Payment $payment) {
        return $payment->session;
    }
],
```

This results in an infinite loop since it is trying to create the PaymentType while trying to create the SessionType which then repeats the process resulting in a loop like this:

```
PHP 220. Illuminate\Support\Facades\Facade::__callStatic() /app/GraphQL/Types/SessionType.php:185
PHP 221. Nuwave\Relay\Schema\GraphQL->type() /vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:216
PHP 222. Nuwave\Relay\Support\Definition\GraphQLType->toType() /vendor/nuwave/laravel-graphql-relay/src/Schema/GraphQL.php:229
PHP 223. Nuwave\Relay\Support\Definition\GraphQLType->toArray() /vendor/nuwave/laravel-graphql-relay/src/Support/Definition/GraphQLType.php:118
PHP 224. Nuwave\Relay\Support\Definition\GraphQLType->getAttributes() /vendor/nuwave/laravel-graphql-relay/src/Support/Definition/GraphQLType.php:108
PHP 225. Nuwave\Relay\Support\Definition\GraphQLType->getFields() /vendor/nuwave/laravel-graphql-relay/src/Support/Definition/GraphQLType.php:31
PHP 226. Nuwave\Relay\Support\Definition\RelayType->fields() /vendor/nuwave/laravel-graphql-relay/src/Support/Definition/GraphQLType.php:70
PHP 227. App\GraphQL\Types\PaymentType->relayFields() /vendor/nuwave/laravel-graphql-relay/src/Support/Definition/RelayType.php:26
PHP 228. Nuwave\Relay\Facades\GraphQL::type() /app/GraphQL/Types/PaymentType.php:74
PHP 229. Illuminate\Support\Facades\Facade::__callStatic() /app/GraphQL/Types/PaymentType.php:74
PHP 230. Nuwave\Relay\Schema\GraphQL->type() /vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php:216
PHP 231. Nuwave\Relay\Support\Definition\GraphQLType->toType() /vendor/nuwave/laravel-graphql-relay/src/Schema/GraphQL.php:229
PHP 232. Nuwave\Relay\Support\Definition\GraphQLType->toArray() /vendor/nuwave/laravel-graphql-relay/src/Support/Definition/GraphQLType.php:118
PHP 233. Nuwave\Relay\Support\Definition\GraphQLType->getAttributes() /vendor/nuwave/laravel-graphql-relay/src/Support/Definition/GraphQLType.php:108
PHP 234. Nuwave\Relay\Support\Definition\GraphQLType->getFields() /vendor/nuwave/laravel-graphql-relay/src/Support/Definition/GraphQLType.php:31
PHP 235. Nuwave\Relay\Support\Definition\RelayType->fields() /vendor/nuwave/laravel-graphql-relay/src/Support/Definition/GraphQLType.php:70
PHP 236. App\GraphQL\Types\SessionType->relayFields() /vendor/nuwave/laravel-graphql-relay/src/Support/Definition/RelayType.php:26
PHP 237. Nuwave\Relay\Facades\GraphQL::type() /app/GraphQL/Types/SessionType.php:185
PHP 238. Illuminate\Support\Facades\Facade::__callStatic() /app/GraphQL/Types/SessionType.php:185
...
```

**Comment by chrissm79** [comment]
Can't believe I haven't run into this myself on numerous occasions, but thanks for reporting it! Looks like [graphql-php](https://github.com/webonyx/graphql-php/issues/16) pushed a fix for it awhile back. If you update the package to `v0.3.2` it should now be resolved, but let me know if you still have issues.

**Comment by davidstoker** [comment]
Fantastic, that took care of it! Thanks for the quick response @chrissm79!

**Comment by mohamed-alashry** [comment]
still not working for me and the package updated to `v0.5.2`

**Comment by mohamed-alashry** [comment]
I can't make it work with relay, well i'm new to it!  i did the back-end part and i don't know how to make it work or how to try it. any help i'll be thankful.

**Comment by bcarroll22** [comment]
So, when you have these situations where you have types that can reference each other, you can avoid this infinite loop by making the type a callback. What you'd wanna do is: 

```
'payments' => [
    'type' => function () {
        return Type::listOf(GraphQL::type('payment'));
    },
    'description' => 'Payments for session',
    'resolve' => function (Session $session) {
        return $session->payments;
    }
],
```

```
'session' => [
    'type' => function () {
        return GraphQL::type('session');
    },
    'description' => 'Session that payment is connected to',
    'resolve' => function (Payment $payment) {
        return $payment->session;
    }
],
```

This will avoid the segfault you're encountering. It's not a bug with any package, it's expected behavior.

**Comment by spawnia** [comment]
This project is deprecated in favor of https://github.com/nuwave/lighthouse
